Feat: 스터디 룸 나가기 기능 및 컴포넌트 개발
Pomodoro-mate/Pomodoro-mate-frontend pull request #19
Opened 2024-04-23 14:46 UTC by jungjinbeom

- 스터디 룸 나가기 confirm modal 컴포넌트 개발 및 Context hook 개발
- 스터디 룸 나기기 시 나가기 API 호출 , 경로 이동 , 뒤로가기 Block해제 로직 추가  
- 스터디 중 뒤로가기 시 뒤로가기 버튼 Block 기능 추가 
- 스터디 룸 나가기 API 필요한 participantId 값 LocalStorage 에 저장

2024-04-23 17:01 UTC, Seung-wan reviewed
저는 지금 구조처럼 분리하는게 더 좋은 것 같은데요.
`ExitRoomModalProvider`자체는 모달을 관리하는 역할을 담당하고 있고, 이 모달의 동작은 커스텀 훅으로 추상화되는게 괜찮을 것 같습니다.

2024-04-23 17:01 UTC, Seung-wan commented on src/apis/study-room/create-study-room.ts
> +      restingTime: 20,
DEFAULT_TIME 이런 느낌으로? 상수화해서 표현해줘도 좋을 것 같습니다~

2024-04-23 17:01 UTC, Seung-wan commented on src/apis/study-room/exit-study-room.ts
> +};
다른 파일에서는 함수명+Param으로 표현해주고 있어서 그대로 따라주면 좋을 것 같아요!
```suggestion
type ExitStudyRoomParam = {
  studyRoomId: number;
  participantId: number;
};
```

2024-04-23 17:01 UTC, Seung-wan commented on src/apis/study-room/exit-study-room.ts
> +};
근데 현재 구조에서는 하나의 파일당 하나의 함수라서 오히려 Param으로 표현하는 컨벤션으로 가도 괜찮을 것 같기도 하네요~ 사소하지만 Param보다는 Params가 어떨까 싶습니다~

2024-04-23 17:01 UTC, Seung-wan commented on src/apis/study-room/exit-study-room.ts
> +  return await http.delete(`/studyrooms/${studyRoomId}/participants/${participantId}`);
해당 api는 리턴값이 있나요?

2024-04-23 17:01 UTC, Seung-wan commented on src/pages/study-room/components/header.tsx
>    return (
return문 전에는 확실히 개행이 들어가는게 코드를 읽는데 깔끔하다고 생각합니다~

2024-04-23 17:01 UTC, Seung-wan commented on src/pages/study-room/hooks/useExitStudyRoom.ts
> +  const { mutate } = useExitStudyRoomMutation();
mutate 그대로 사용하기보다 의도를 더 드러내주면 좋을 것 같습니다~

2024-04-23 17:01 UTC, Seung-wan commented on src/pages/study-room/hooks/useExitStudyRoom.ts
> +    const participantId = getLocalStorage('participantId');
서비스 규모가 커지면 문자열 리터럴로 로컬스토리지에서 값을 가져오는 것은 위험성이 있는 코드같아요~
class나 closure를 이용해서 key값을 내부에 감춰놓은 스토리지 모듈을 만들거나 key값을 상수화해서 다루면 좋을 것 같습니다~

2024-04-23 17:01 UTC, Seung-wan commented on src/pages/study-room/hooks/useExitStudyRoom.ts
> +    mutate({ studyRoomId: Number(studyId), participantId: Number(participantId) });
studyId를 받아오는 시점, participantId를 받아오는 시점에 미리 형변환을 해주는건 어떨까요?

2024-04-23 17:01 UTC, Seung-wan commented on src/pages/study-room/hooks/useExitStudyRoom.ts
> +    if (state !== 'blocked') return;
조건식을 변수로 분리해서 의도를 드러내주면 코드를 이해하는데 더 좋을 것 같아요~
useBlocker훅이 익숙하지 않다면 return하고 있는 state값을 이해하기가 어려울 것 같네요~

2024-04-23 17:01 UTC, Seung-wan commented on src/pages/study-room/hooks/useExitStudyRoom.ts
> +    mutate({ studyRoomId: Number(studyId), participantId: Number(participantId) });
mutate가 실패했을때 proceed를 실행해도 괜찮을까요?

2024-04-23 17:01 UTC, Seung-wan commented on src/pages/study-rooms/components/create-study-room-modal.tsx
> +      const { id, participantId } = await createStudyRoom({ name, intro });
여기서는 useMutation없이 api 함수를 그대로 사용해주신 이유가 있을까요?

2024-04-23 17:01 UTC, Seung-wan commented on src/pages/study-rooms/components/create-study-room-modal.tsx
> +      setLocalStorage({ key: 'participantId', value: String(participantId) });
이런 인터페이스로 사용되는게 좋을 것 같습니다~
```suggestion
      setLocalStorage('participantId', String(participantId));
```

2024-04-23 17:01 UTC, Seung-wan commented on src/pages/study-room/provider/exit-room-modal-provier.tsx
> +  const closeDialog = () => setIsOpen(false);
이 코드는 커스텀훅으로 표현되어도 좋을 것 같습니다~
```ts
const [isOpen, openDialog, closeDialog] = useBooleanState();
```

[useBooleanState](https://github.com/toss/slash/blob/main/packages/react/react/src/hooks/useBooleanState.ts)

2024-04-23 17:01 UTC, Seung-wan commented on src/pages/study-room/provider/exit-room-modal-provier.tsx
> +    exitStudyRoom();
이게 실패해도 다음 함수들이 실행되도 괜찮은지를 확인해보면 좋을 것 같습니다~

2024-04-23 17:01 UTC, Seung-wan commented on src/pages/study-room/provider/exit-room-modal-provier.tsx
> +      )}
아래 코드랑
```ts
      {isOpen && (
        <Modal
          isOpen={isOpen}
          title="스터디룸 생성"
          closeBtn="취소"
          actionBtn="나가기"
          onClickActionBtn={clickExit}
          onClose={closeDialog}
        >
          <Typography>스터디 방을 나가시겠습니까?</Typography>
        </Modal>
      )}
```
아래 코드중에 뭐가 괜찮을까요?
```ts
        <Modal
          isOpen={isOpen}
          title="스터디룸 생성"
          closeBtn="취소"
          actionBtn="나가기"
          onClickActionBtn={clickExit}
          onClose={closeDialog}
        >
          <Typography>스터디 방을 나가시겠습니까?</Typography>
        </Modal>
```

2024-04-23 17:01 UTC, Seung-wan commented on src/pages/study-room/provider/exit-room-modal-provier.tsx
> +          <Typography>스터디 방을 나가시겠습니까?</Typography>
모달에 children이 들어갈 때 지금처럼 합성 컴포넌트로 표현되지 않으면 실제로 children이 어디에 렌더링될지 알기 어려운 것 같아서 합성 컴포넌트로 표현되거나, props로 표현되면 어떨까 싶기도 하네요~

2024-04-23 17:01 UTC, Seung-wan commented on src/pages/study-room/study-room.tsx
> +    window.addEventListener('popstate', handlePopState);
래핑하는 handlePopState 함수를 만들기보다 이렇게 그대로 표현해줘도 괜찮지 않을까요?
```suggestion
    window.addEventListener('popstate', openDialog);
```

2024-04-23 17:01 UTC, Seung-wan commented on src/pages/study-room/study-room.tsx
> +    // 컴포넌트가 언마운트될 때 이벤트 리스너 제거
여기서는 코드를 이해하는데 큰 어려움이 없기 때문에 이런 주석은 제거되면 좋을 것 같습니다~

2024-04-23 17:01 UTC, Seung-wan commented on src/pages/study-room/study-room.tsx
> +      window.addEventListener('popstate', handlePopState);
이렇게 되어야하지 않을까요?
```suggestion
      window.removeEventListener('popstate', handlePopState);
```

2024-04-23 17:02 UTC, Seung-wan commented on src/pages/study-room/provider/exit-room-modal-provier.tsx
> +const ExitRoomModalProvier = ({ children }: PropsWithChildren) => {
오타있네요~ VSCode의 `Code Spell Checker` 익스텐션을 사용하지 않으신다면 사용하시면 좋을 것 같습니다~
```suggestion
const ExitRoomModalProvider = ({ children }: PropsWithChildren) => {
```

2024-04-26 15:09 UTC, jungjinbeom commented on src/pages/study-room/provider/exit-room-modal-provier.tsx
> +          <Typography>스터디 방을 나가시겠습니까?</Typography>
이부분은 공통 모달을 수정해야해서 프론트 개발자분과 상의해서 어떻게 수정해야 할지 정해야될거 같아요. 말씀대로 Modal이라는 컴포넌트는 버튼과 콘텐츠 등을 보여주기 때문에 props 사용해서 어디로 렌더링되는지 보여주면 개발자 입장에서는 편할거 같아요

2024-04-26 15:09 UTC, jungjinbeom commented on src/pages/study-room/hooks/useExitStudyRoom.ts
> +  const { mutate } = useExitStudyRoomMutation();
가독성 측면에서 이점이 있겠네요 !!

2024-04-26 15:09 UTC, jungjinbeom commented on src/pages/study-room/hooks/useExitStudyRoom.ts
> +    if (state !== 'blocked') return;
가독성 측면도 그렇고 명확하게 무엇을 하는지 나타는게 사용자 입장에서 좋겠네요 !!

2024-04-26 15:09 UTC, jungjinbeom commented on src/pages/study-room/study-room.tsx
> +    window.addEventListener('popstate', handlePopState);
빼다고 했는데 깜빡했네요 ㅠㅠ

2024-04-26 15:09 UTC, jungjinbeom commented on src/pages/study-room/study-room.tsx
> +      window.addEventListener('popstate', handlePopState);
복붙에 폐해네요ㅠㅠ 수정하겠습니다

2024-04-26 15:09 UTC, jungjinbeom commented on src/pages/study-rooms/components/create-study-room-modal.tsx
> +      const { id, participantId } = await createStudyRoom({ name, intro });
API 호출에 대한 규칙을 정하기 전에 작성해서 그런거 같아요 담당개발자와 의논후 수정하겠습니다!

2024-04-26 15:09 UTC, jungjinbeom commented on src/pages/study-rooms/components/create-study-room-modal.tsx
> +      setLocalStorage({ key: 'participantId', value: String(participantId) });
storage Class 개발 후 한번에 수정하려고 합니다.

2024-04-26 15:09 UTC, jungjinbeom commented on src/pages/study-room/hooks/useExitStudyRoom.ts
> +    const participantId = getLocalStorage('participantId');
storage Class 개발 후 key값을 상수로 관리할지에 대해 논의 해보겠습니다!

2024-04-26 15:09 UTC, jungjinbeom commented on src/apis/study-room/create-study-room.ts
> +      restingTime: 20,
테스트 데이터여서 상수로 안빼고 삭제했습니다!!

2024-04-26 15:09 UTC, jungjinbeom commented on src/apis/study-room/exit-study-room.ts
> +};
전체적으로 api 타입명에 대해 의논해서 컨벤션을 잡도록 해봐야겠습니다!

2024-04-26 15:09 UTC, jungjinbeom commented on src/pages/study-room/provider/exit-room-modal-provier.tsx
> +  const closeDialog = () => setIsOpen(false);
공통 모달 훅으로 빼면 사용성이 좋을거 같네요!!

2024-04-28 06:14 UTC, Seung-wan requested changes

2024-04-28 06:14 UTC, Seung-wan commented on src/apis/study-room/exit-study-room.ts
> +type ExitStudyRoomParam = {
create-study-room.ts 파일에서는 복수형으로 표현해주고 있는데요~
실제로도 여러 값을 받으니까 여기서도 복수형으로 통일해줘도 괜찮을 것 같네요!
```suggestion
type ExitStudyRoomParams = {
```

2024-04-28 06:14 UTC, Seung-wan commented on src/hooks/useBooleanState.ts
> +};
함수는 useCallback으로 래핑해주면 어떨까 싶네요!
그리고 toggle 역할을 하는 함수도 하나 넣어줘도 괜찮을 것 같아요!

2024-04-28 06:14 UTC, Seung-wan commented on src/hooks/useBooleanState.ts
> +  const closeDialog = () => setIsOpen(false);
상태명과 함수명에 특정 맥락이 들어가있는 것 같아요.
상태에서는 true, false가 open이라는 맥락과 엮여있고, 함수에서는 open/close + dialog라는 맥락이랑 엮여있네요.

useBooleanState라는 훅 자체는 정말 단순히 boolean 데이터를 true, false로만 바꾸게 되고 이 상태를 어떤 도메인 맥락에서 사용할지는 외부에서 정해야 할 것 같아요.

2024-04-28 06:14 UTC, Seung-wan commented on src/pages/study-room/hooks/useExitStudyRoom.ts
> +  const { mutate } = useExitStudyRoomMutation();
mutate 함수의 네이밍을 변경해서 쓰는 것도 반영해주시면 좋을 것 같습니다~

2024-04-28 06:14 UTC, Seung-wan commented on src/pages/study-room/hooks/useExitStudyRoom.ts
> +    if (state !== 'blocked') return;
여기도 반영은 안된 것 같네요!

2024-04-28 06:14 UTC, Seung-wan commented on src/pages/study-room/hooks/useExitStudyRoom.ts
> +      { onSuccess: () => proceed() },
이렇게 표현해줘도 괜찮을 것 같네요!
```suggestion
      { onSuccess:  proceed },
```

2024-04-28 06:14 UTC, Seung-wan commented on src/pages/study-room/hooks/useExitStudyRoom.ts
> +      { onSuccess: () => proceed() },
그리고 onSuccess 콜백을 useExitStudyRoomMutation 훅을 사용하는 쪽에서 정의해주면 코드를 읽을때 mutate가 되었을 때 어떤 일이 일어날지 더욱 명확하게 이해하기 좋을 것 같아요.

2024-04-28 06:14 UTC, Seung-wan commented on src/pages/study-room/provider/exit-room-modal-provider.tsx
> +  openDialog: () => {},
Modal이랑 Dialog라는 단어가 두개가 쓰이고 있어서 조금 헷갈릴수도 있을 것 같네요!

2024-04-28 06:14 UTC, Seung-wan commented on src/pages/study-room/provider/exit-room-modal-provider.tsx
> +    exitStudyRoom();
이 함수가 실패했을때도 다음 동작이 진행되어도 괜찮은걸까요? 
데이터 상으로는 나가지지 않았지만 UI적으로는 나가진걸로 표현이 될 것 같아서요.

2024-04-28 06:14 UTC, Seung-wan commented on src/pages/study-room/study-room.tsx
> +      window.addEventListener('popstate', handlePopState);
반영되지 않은 것 같습니다~

2024-04-28 06:14 UTC, Seung-wan commented on src/pages/study-room/study-room.tsx
> +    window.addEventListener('popstate', handlePopState);
여기도 동일합니다!

2024-05-01 15:16 UTC, junhyeong00 approved these changes

2024-05-02 13:46 UTC, merged